lists:
  - name: trackers
    data:
      - name: EasyList
        attribution: The EasyList authors (https://easylist.to/)
        license: GPL-3.0
        sources:
          - 'https://easylist.to/easylist/easylist.txt'
          - 'https://easylist.to/easylist/easyprivacy.txt'

      - name: Energized Ultimate
        attribution: https://github.com/EnergizedProtection/block/blob/master/LICENSE
        license: MIT
        sources:
          - 'https://block.energized.pro/ultimate/formats/filter'

      - name: Dot HQ Ad Blocking
        attribution: https://github.com/dothq/blocking-lists/blob/main/lists/LICENSE
        license: MPL-2.0
        sources:
          - 'https://raw.githubusercontent.com/dothq-extensions/shield-db/main/lists/ads.txt'

      - name: uBO Lists
        attribution: https://github.com/uBlockOrigin/uAssets/blob/master/LICENSE
        license: GPL-3.0
        sources:
          - 'https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/filters-2020.txt'
          - 'https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/filters-2021.txt'
          - 'https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/filters-2022.txt'
      
      - name: Adguard Filters
        attribution: https://github.com/AdguardTeam/AdguardFilters/blob/master/LICENSE
        license: GPL-3.0
        sources:
          - 'https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_14_Annoyances/filter.txt'
          - 'https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_2_English/filter.txt'

  - name: social
    data:
      - name: Energized Social Extension
        attribution: https://github.com/EnergizedProtection/block/blob/master/LICENSE
        license: MIT
        sources:
          - 'https://block.energized.pro/extensions/social/formats/filter'

      - name: Adguard Filters
        attribution: https://github.com/AdguardTeam/AdguardFilters/blob/master/LICENSE
        license: GPL-3.0
        sources:
          - 'https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_4_Social/filter.txt'

      - name: Dot HQ Ad Blocking
        attribution: https://github.com/dothq/blocking-lists/blob/main/lists/LICENSE
        license: MPL-2.0
        sources:
          - 'https://raw.githubusercontent.com/dothq-extensions/shield-db/main/lists/social.txt'

      - name: Fanboy Filters
        attribution: http://creativecommons.org/licenses/by/3.0/
        license: CC BY 3.0
        sources:
          - 'https://easylist.to/easylist/fanboy-social.txt'

  - name: annoyances
    data:
      - name: Fanboy Filters
        attribution: http://creativecommons.org/licenses/by/3.0/
        license: CC BY 3.0
        sources:
          - 'https://secure.fanboy.co.nz/fanboy-annoyance.txt'

      - name: Adguard Filters
        attribution: https://github.com/AdguardTeam/AdguardFilters/blob/master/LICENSE
        license: GPL-3.0
        sources:
          - 'https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_14_Annoyances/filter.txt'

      - name: Web Annoyances
        attribution: https://creativecommons.org/licenses/by-sa/4.0
        license: CC BY-SA 4.0
        sources:
          - 'https://raw.githubusercontent.com/yourduskquibbles/webannoyances/master/ultralist.txt'

  - name: ip_grabbers
    data:
      - name: Dot HQ IP Grabber Blocking
        attribution: https://github.com/dothq/blocking-lists/blob/main/lists/LICENSE
        license: MPL-2.0
        sources:
          - 'https://raw.githubusercontent.com/dothq-extensions/shield-db/main/lists/ip_grabbers.txt'
