trackers:
  abp:
    - 'https://easylist.to/easylist/easylist.txt'
    - 'https://easylist.to/easylist/easyprivacy.txt'
    - 'https://hosts.netlify.app/Pro/adblock.txt'
    - 'https://raw.githubusercontent.com/trickypr/energized-mirror/main/ultimate.txt'

social:
  abp:
    - 'https://raw.githubusercontent.com/trickypr/energized-mirror/main/social.txt'
