name: ShieldDB
out: out

header:
  creator: Dot HQ
  product: Dot Shield (adblocker)

lists:
  - name: trackers
    abp:
      - 'https://easylist.to/easylist/easylist.txt'
      - 'https://easylist.to/easylist/easyprivacy.txt'
      - 'https://hosts.netlify.app/Pro/adblock.txt'
      # - 'https://raw.githubusercontent.com/trickypr/energized-mirror/main/ultimate.txt'
      - 'https://raw.githubusercontent.com/dothq-extensions/shield-db/main/lists/ads.txt'
      - 'https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/filters-2021.txt'
      - 'https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_14_Annoyances/filter.txt'
      - 'https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_2_English/filter.txt'

    hosts: []

  - name: social
    abp:
      - 'https://raw.githubusercontent.com/trickypr/energized-mirror/main/social.txt'
      - 'https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_4_Social/filter.txt'
      - 'https://raw.githubusercontent.com/dothq-extensions/shield-db/main/lists/social.txt'

    hosts: []

  - name: fake_news
    abp: []

    hosts:
      - 'https://raw.githubusercontent.com/StevenBlack/hosts/master/extensions/fakenews/hosts'

  - name: annoyances
    abp:
      - 'https://secure.fanboy.co.nz/fanboy-cookiemonster.txt'
      - 'https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_14_Annoyances/filter.txt'
      
    hosts: []

  - name: clean_web
    abp:
      - 'https://raw.githubusercontent.com/yourduskquibbles/webannoyances/master/ultralist.txt'      
    hosts: []

  - name: gambling
    abp: []

    hosts:
      - 'https://raw.githubusercontent.com/StevenBlack/hosts/master/extensions/gambling/hosts'

  - name: ip_grabbers
    abp: []

    hosts:
      - 'https://raw.githubusercontent.com/ejaz4/hosts/main/IP%20loggers.txt'
