name: Compile lists

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * *'
  push:
    branches:
      - main

jobs:
  compile:
    name: Compile lists
    runs-on: ubuntu-latest
    steps:
      - name: Checkout...
        uses: actions/checkout@v2

      - name: Compile...
        run: cargo run

      - name: Upload changes...
        uses: EndBug/add-and-commit@v6
        with:
          author_email: dothq-robot@users.noreply.github.com
          author_name: dothq-robot
          token: ${{ secrets.ROBOT_TOKEN }}
          message: '👽 Update blocking lists'